version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: skills-backend-repo
    IMAGE_TAG: latest
    AWS_REGION: us-east-1
    ECR_URI: 557825993708.dkr.ecr.us-east-1.amazonaws.com
    IMAGE_URI: 557825993708.dkr.ecr.us-east-1.amazonaws.com/skills-backend-repo:latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
      - echo Build started on `date`
  build:
    commands:
      - echo Building project with Gradle...
      - chmod +x gradlew
      - ./gradlew build -x test
      - ls -lh build/libs
      - echo Building the Docker image...
      - docker build -t $IMAGE_URI .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $IMAGE_URI
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"backend","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json